-- =============================================================================
-- HERCOSSNUX PQC IP Core - Layer 3B
-- ntt_d_tables_pkg: constants and root table for the ML-DSA NTT-D datapath.
-- Generated by ntt_d/gen_ntt_d.py. VHDL-2008. ASCII-only. MIT license.
--
-- q = 8380417, R = 2^32.
--
-- C_QINVD is q^-1 mod 2^32 for the SUBTRACTIVE Montgomery convention
--   t = (a * C_QINVD) truncated to signed 32 bits
--   r = (a - t * q) >> 32
-- The value 4236238847 seen elsewhere is -q^-1 mod 2^32 and belongs to the
-- additive convention; using it here silently produces wrong products.
--
-- Zetas are stored PRE-CONVERTED to the Montgomery domain as signed values,
-- so a butterfly is one multiply and one reduction with no extra lift.
-- =============================================================================
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package ntt_d_tables_pkg is

  constant C_QD    : integer := 8380417;
  constant C_QINVD : integer := 58728449;
  -- R^2 mod q, used to lift one basemul operand into the Montgomery domain
  constant C_RD2   : integer := 2365951;
  -- 256^-1 in the Montgomery domain, the final INTT scale
  constant C_SD    : integer := 16382;

  -- Coefficients are signed 32-bit. Worst observed growth without
  -- intermediate reduction is 28015249 forward and 99120476 inverse,
  -- so 32 bits leaves more than fourfold headroom.
  constant C_CW    : integer := 32;

  type t_zeta_d is array (0 to 255) of signed(23 downto 0);
  constant C_ZETAS_D : t_zeta_d := (
    to_signed(-4186625, 24), to_signed(25847, 24), to_signed(-2608894, 24), to_signed(-518909, 24),
    to_signed(237124, 24), to_signed(-777960, 24), to_signed(-876248, 24), to_signed(466468, 24),
    to_signed(1826347, 24), to_signed(2353451, 24), to_signed(-359251, 24), to_signed(-2091905, 24),
    to_signed(3119733, 24), to_signed(-2884855, 24), to_signed(3111497, 24), to_signed(2680103, 24),
    to_signed(2725464, 24), to_signed(1024112, 24), to_signed(-1079900, 24), to_signed(3585928, 24),
    to_signed(-549488, 24), to_signed(-1119584, 24), to_signed(2619752, 24), to_signed(-2108549, 24),
    to_signed(-2118186, 24), to_signed(-3859737, 24), to_signed(-1399561, 24), to_signed(-3277672, 24),
    to_signed(1757237, 24), to_signed(-19422, 24), to_signed(4010497, 24), to_signed(280005, 24),
    to_signed(2706023, 24), to_signed(95776, 24), to_signed(3077325, 24), to_signed(3530437, 24),
    to_signed(-1661693, 24), to_signed(-3592148, 24), to_signed(-2537516, 24), to_signed(3915439, 24),
    to_signed(-3861115, 24), to_signed(-3043716, 24), to_signed(3574422, 24), to_signed(-2867647, 24),
    to_signed(3539968, 24), to_signed(-300467, 24), to_signed(2348700, 24), to_signed(-539299, 24),
    to_signed(-1699267, 24), to_signed(-1643818, 24), to_signed(3505694, 24), to_signed(-3821735, 24),
    to_signed(3507263, 24), to_signed(-2140649, 24), to_signed(-1600420, 24), to_signed(3699596, 24),
    to_signed(811944, 24), to_signed(531354, 24), to_signed(954230, 24), to_signed(3881043, 24),
    to_signed(3900724, 24), to_signed(-2556880, 24), to_signed(2071892, 24), to_signed(-2797779, 24),
    to_signed(-3930395, 24), to_signed(-1528703, 24), to_signed(-3677745, 24), to_signed(-3041255, 24),
    to_signed(-1452451, 24), to_signed(3475950, 24), to_signed(2176455, 24), to_signed(-1585221, 24),
    to_signed(-1257611, 24), to_signed(1939314, 24), to_signed(-4083598, 24), to_signed(-1000202, 24),
    to_signed(-3190144, 24), to_signed(-3157330, 24), to_signed(-3632928, 24), to_signed(126922, 24),
    to_signed(3412210, 24), to_signed(-983419, 24), to_signed(2147896, 24), to_signed(2715295, 24),
    to_signed(-2967645, 24), to_signed(-3693493, 24), to_signed(-411027, 24), to_signed(-2477047, 24),
    to_signed(-671102, 24), to_signed(-1228525, 24), to_signed(-22981, 24), to_signed(-1308169, 24),
    to_signed(-381987, 24), to_signed(1349076, 24), to_signed(1852771, 24), to_signed(-1430430, 24),
    to_signed(-3343383, 24), to_signed(264944, 24), to_signed(508951, 24), to_signed(3097992, 24),
    to_signed(44288, 24), to_signed(-1100098, 24), to_signed(904516, 24), to_signed(3958618, 24),
    to_signed(-3724342, 24), to_signed(-8578, 24), to_signed(1653064, 24), to_signed(-3249728, 24),
    to_signed(2389356, 24), to_signed(-210977, 24), to_signed(759969, 24), to_signed(-1316856, 24),
    to_signed(189548, 24), to_signed(-3553272, 24), to_signed(3159746, 24), to_signed(-1851402, 24),
    to_signed(-2409325, 24), to_signed(-177440, 24), to_signed(1315589, 24), to_signed(1341330, 24),
    to_signed(1285669, 24), to_signed(-1584928, 24), to_signed(-812732, 24), to_signed(-1439742, 24),
    to_signed(-3019102, 24), to_signed(-3881060, 24), to_signed(-3628969, 24), to_signed(3839961, 24),
    to_signed(2091667, 24), to_signed(3407706, 24), to_signed(2316500, 24), to_signed(3817976, 24),
    to_signed(-3342478, 24), to_signed(2244091, 24), to_signed(-2446433, 24), to_signed(-3562462, 24),
    to_signed(266997, 24), to_signed(2434439, 24), to_signed(-1235728, 24), to_signed(3513181, 24),
    to_signed(-3520352, 24), to_signed(-3759364, 24), to_signed(-1197226, 24), to_signed(-3193378, 24),
    to_signed(900702, 24), to_signed(1859098, 24), to_signed(909542, 24), to_signed(819034, 24),
    to_signed(495491, 24), to_signed(-1613174, 24), to_signed(-43260, 24), to_signed(-522500, 24),
    to_signed(-655327, 24), to_signed(-3122442, 24), to_signed(2031748, 24), to_signed(3207046, 24),
    to_signed(-3556995, 24), to_signed(-525098, 24), to_signed(-768622, 24), to_signed(-3595838, 24),
    to_signed(342297, 24), to_signed(286988, 24), to_signed(-2437823, 24), to_signed(4108315, 24),
    to_signed(3437287, 24), to_signed(-3342277, 24), to_signed(1735879, 24), to_signed(203044, 24),
    to_signed(2842341, 24), to_signed(2691481, 24), to_signed(-2590150, 24), to_signed(1265009, 24),
    to_signed(4055324, 24), to_signed(1247620, 24), to_signed(2486353, 24), to_signed(1595974, 24),
    to_signed(-3767016, 24), to_signed(1250494, 24), to_signed(2635921, 24), to_signed(-3548272, 24),
    to_signed(-2994039, 24), to_signed(1869119, 24), to_signed(1903435, 24), to_signed(-1050970, 24),
    to_signed(-1333058, 24), to_signed(1237275, 24), to_signed(-3318210, 24), to_signed(-1430225, 24),
    to_signed(-451100, 24), to_signed(1312455, 24), to_signed(3306115, 24), to_signed(-1962642, 24),
    to_signed(-1279661, 24), to_signed(1917081, 24), to_signed(-2546312, 24), to_signed(-1374803, 24),
    to_signed(1500165, 24), to_signed(777191, 24), to_signed(2235880, 24), to_signed(3406031, 24),
    to_signed(-542412, 24), to_signed(-2831860, 24), to_signed(-1671176, 24), to_signed(-1846953, 24),
    to_signed(-2584293, 24), to_signed(-3724270, 24), to_signed(594136, 24), to_signed(-3776993, 24),
    to_signed(-2013608, 24), to_signed(2432395, 24), to_signed(2454455, 24), to_signed(-164721, 24),
    to_signed(1957272, 24), to_signed(3369112, 24), to_signed(185531, 24), to_signed(-1207385, 24),
    to_signed(-3183426, 24), to_signed(162844, 24), to_signed(1616392, 24), to_signed(3014001, 24),
    to_signed(810149, 24), to_signed(1652634, 24), to_signed(-3694233, 24), to_signed(-1799107, 24),
    to_signed(-3038916, 24), to_signed(3523897, 24), to_signed(3866901, 24), to_signed(269760, 24),
    to_signed(2213111, 24), to_signed(-975884, 24), to_signed(1717735, 24), to_signed(472078, 24),
    to_signed(-426683, 24), to_signed(1723600, 24), to_signed(-1803090, 24), to_signed(1910376, 24),
    to_signed(-1667432, 24), to_signed(-1104333, 24), to_signed(-260646, 24), to_signed(-3833893, 24),
    to_signed(-2939036, 24), to_signed(-2235985, 24), to_signed(-420899, 24), to_signed(-2286327, 24),
    to_signed(183443, 24), to_signed(-976891, 24), to_signed(1612842, 24), to_signed(-3545687, 24),
    to_signed(-554416, 24), to_signed(3919660, 24), to_signed(-48306, 24), to_signed(-1362209, 24),
    to_signed(3937738, 24), to_signed(1400424, 24), to_signed(-846154, 24), to_signed(1976782, 24));

end package ntt_d_tables_pkg;
