library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity tb_framegen is
end entity;

architecture sim of tb_framegen is
  signal clk : std_logic := '0';
  signal rst : std_logic := '1';
  signal start : std_logic := '0';
  signal byte_out : std_logic_vector(7 downto 0);
  signal byte_valid : std_logic;
  signal busy, done : std_logic;
begin
  clk <= not clk after 5 ns;

  dut : entity work.frame_gen
    generic map (W=>128, H=>96, BAR_W=>16)
    port map (clk=>clk, rst=>rst, start=>start, stall=>'0',
              byte_out=>byte_out, byte_valid=>byte_valid, busy=>busy, done=>done);

  -- checker: read golden stream, compare each generated byte
  check : process
    file fh : text;
    variable ln : line;
    variable gv : std_logic_vector(7 downto 0);
    variable ok : file_open_status;
    variable idx : integer := 0;
    variable mismatches : integer := 0;
  begin
    file_open(ok, fh, "gold_stream.hex", read_mode);
    assert ok=open_ok report "no gold_stream.hex" severity failure;

    rst <= '1'; start <= '0';
    wait for 40 ns; wait until rising_edge(clk);
    rst <= '0'; wait until rising_edge(clk);
    start <= '1'; wait until rising_edge(clk);
    start <= '0';

    -- collect every valid byte and compare
    while not endfile(fh) loop
      wait until rising_edge(clk);
      if byte_valid = '1' then
        readline(fh, ln); hread(ln, gv);
        if byte_out /= gv then
          if mismatches < 10 then
            report "MISMATCH at "&integer'image(idx)&
                   " gen=0x"&to_hstring(byte_out)&" gold=0x"&to_hstring(gv)
              severity warning;
          end if;
          mismatches := mismatches + 1;
        end if;
        idx := idx + 1;
      end if;
    end loop;
    file_close(fh);

    report "frame_gen bytes compared = "&integer'image(idx)&
           " mismatches = "&integer'image(mismatches);
    if mismatches = 0 and idx = 38032 then
      report "FRAMEGEN PASS - byte-identical to oracle ("&integer'image(idx)&" bytes)"
        severity note;
    else
      report "FRAMEGEN FAIL" severity failure;
    end if;
    wait;
  end process;
end architecture;
