# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.runs/synth_1/bd_soc_usart_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param ced.repoPaths /home/adrian/Downloads/TE0950_Designs/04_AMD_Vivado_Custom_Configurable_Example
set_param bd.open.in_stealth_mode 3
set_param general.usePosixSpawnForFork 1
set_param chipscope.flow 0
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcve2302-sfva784-1LP-e-S

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.cache/wt [current_project]
set_property parent.project_path /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/adrian/te0950_work/board_files} [current_project]
set_property board_part trenz.biz:te0950_23_1lse:part0:1.2 [current_project]
set_property ip_output_repo /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/hdl/bd_soc_usart_wrapper.v
add_files /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.srcs/sources_1/bd/bd_soc_usart/bd_soc_usart.bd
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_0/bd_9435_pspmc_0_0.xdc]
set_property used_in_synthesis false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_1/bd_9435_xram_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/bd_9435_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_b77b_S05_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_b77b_S03_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_b77b_S04_AXI_rpu_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_b77b_S02_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_b77b_S06_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_b77b_S01_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_b77b_S00_AXI_nmu_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/hdl/par/bd_b77b_MC0_ddrc_0_ip.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_1/bd_7e15_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_5/bd_7e15_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_6/bd_7e15_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_7/bd_7e15_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_8/bd_7e15_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_9/bd_7e15_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_10/bd_7e15_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_0/ip/ip_11/bd_7e15_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/smartconnect.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/bd_soc_usart_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/ip_0/bd_b77b_MC0_ddrc_0_phy_ddrmc.elf]
set_property used_in_synthesis false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/nsln/bd_soc_usart.nts]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/nsln/bd_soc_usart.nts]
set_property used_in_synthesis false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/nsln/bd_soc_usart.ncr]
set_property used_in_implementation false [get_files -all /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/nsln/bd_soc_usart.ncr]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/adrian/m1553_ip/m1553_pins.xdc
set_property used_in_implementation false [get_files /home/adrian/m1553_ip/m1553_pins.xdc]

read_xdc /home/adrian/eth_ip/eth_pins.xdc
set_property used_in_implementation false [get_files /home/adrian/eth_ip/eth_pins.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top bd_soc_usart_wrapper -part xcve2302-sfva784-1LP-e-S
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bd_soc_usart_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file bd_soc_usart_wrapper_utilization_synth.rpt -pb bd_soc_usart_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
