# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/adrian/m1553_ip/m1553_pins.xdc

# XDC: /home/adrian/eth_ip/eth_pins.xdc

# Block Designs: bd/bd_soc_usart/bd_soc_usart.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_soc_usart || ORIG_REF_NAME==bd_soc_usart} -quiet] -quiet

# IP: bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_soc_usart_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_soc_usart_versal_cips_0_0 || ORIG_REF_NAME==bd_soc_usart_versal_cips_0_0} -quiet] -quiet

# Block Designs: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/bd_9435.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9435 || ORIG_REF_NAME==bd_9435} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_0/bd_9435_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9435_pspmc_0_0 || ORIG_REF_NAME==bd_9435_pspmc_0_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_1/bd_9435_xram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9435_xram_0 || ORIG_REF_NAME==bd_9435_xram_0} -quiet] -quiet

# IP: bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_soc_usart_axi_noc_0_0 || ORIG_REF_NAME==bd_soc_usart_axi_noc_0_0} -quiet] -quiet

# IP: bd/bd_soc_usart/ip/bd_soc_usart_axi_smc_0/bd_soc_usart_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_soc_usart_axi_smc_0 || ORIG_REF_NAME==bd_soc_usart_axi_smc_0} -quiet] -quiet

# IP: bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_soc_usart_rst_versal_cips_0_240M_0 || ORIG_REF_NAME==bd_soc_usart_rst_versal_cips_0_240M_0} -quiet] -quiet

# IP: bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_soc_usart_u_soc_ptp_0 || ORIG_REF_NAME==bd_soc_usart_u_soc_ptp_0} -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_0/bd_9435_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9435_pspmc_0_0 || ORIG_REF_NAME==bd_9435_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9435_pspmc_0_0 || ORIG_REF_NAME==bd_9435_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/ip/ip_1/bd_9435_xram_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9435_xram_0 || ORIG_REF_NAME==bd_9435_xram_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_versal_cips_0_0/bd_0/bd_9435_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/bd_soc_usart_ooc.xdc
