# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adrian/spw_ip/vivado_spw/spw_soc.srcs/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0.xci
# IP: The module: 'bd_soc_usart_rst_versal_cips_0_240M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/spw_ip/vivado_spw/spw_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_rst_versal_cips_0_240M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/spw_ip/vivado_spw/spw_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_rst_versal_cips_0_240M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/adrian/spw_ip/vivado_spw/spw_soc.srcs/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0.xci
# IP: The module: 'bd_soc_usart_rst_versal_cips_0_240M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/spw_ip/vivado_spw/spw_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_rst_versal_cips_0_240M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/spw_ip/vivado_spw/spw_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_rst_versal_cips_0_240M_0/bd_soc_usart_rst_versal_cips_0_240M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_rst_versal_cips_0_240M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
