# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.srcs/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0.xci
# IP: The module: 'bd_soc_usart_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/bd_b77b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b || ORIG_REF_NAME==bd_b77b} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_0/bd_b77b_S05_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S05_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_1/bd_b77b_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_const_0_0 || ORIG_REF_NAME==bd_b77b_const_0_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_2/bd_b77b_S03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_3/bd_b77b_S04_AXI_rpu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_b77b_S04_AXI_rpu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_4/bd_b77b_S02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_5/bd_b77b_S06_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S06_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_6/bd_b77b_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_7/bd_b77b_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/bd_b77b_MC0_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_MC0_ddrc_0 || ORIG_REF_NAME==bd_b77b_MC0_ddrc_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/ip_0/bd_b77b_MC0_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_b77b_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_b77b_S05_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S05_AXI_nmu_0} -quiet] {/bd_b77b_S05_AXI_nmu_0_top_INST } ]/bd_b77b_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_b77b_S03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S03_AXI_nmu_0} -quiet] {/bd_b77b_S03_AXI_nmu_0_top_INST } ]/bd_b77b_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_b77b_S04_AXI_rpu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_b77b_S04_AXI_rpu_0} -quiet] {/bd_b77b_S04_AXI_rpu_0_top_INST } ]/bd_b77b_S04_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_b77b_S02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S02_AXI_nmu_0} -quiet] {/bd_b77b_S02_AXI_nmu_0_top_INST } ]/bd_b77b_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_b77b_S06_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S06_AXI_nmu_0} -quiet] {/bd_b77b_S06_AXI_nmu_0_top_INST } ]/bd_b77b_S06_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_b77b_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S01_AXI_nmu_0} -quiet] {/bd_b77b_S01_AXI_nmu_0_top_INST } ]/bd_b77b_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_b77b_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S00_AXI_nmu_0} -quiet] {/bd_b77b_S00_AXI_nmu_0_top_INST } ]/bd_b77b_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/hdl/par/bd_b77b_MC0_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_MC0_ddrc_0 || ORIG_REF_NAME==bd_b77b_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.srcs/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0.xci
# IP: The module: 'bd_soc_usart_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/bd_b77b.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b || ORIG_REF_NAME==bd_b77b} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_0/bd_b77b_S05_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S05_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_1/bd_b77b_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_const_0_0 || ORIG_REF_NAME==bd_b77b_const_0_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_2/bd_b77b_S03_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S03_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_3/bd_b77b_S04_AXI_rpu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_b77b_S04_AXI_rpu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_4/bd_b77b_S02_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S02_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_5/bd_b77b_S06_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S06_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_6/bd_b77b_S01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S01_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_7/bd_b77b_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S00_AXI_nmu_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/bd_b77b_MC0_ddrc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_MC0_ddrc_0 || ORIG_REF_NAME==bd_b77b_MC0_ddrc_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/ip_0/bd_b77b_MC0_ddrc_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_b77b_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_b77b_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_b77b_S05_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S05_AXI_nmu_0} -quiet] {/bd_b77b_S05_AXI_nmu_0_top_INST } ]/bd_b77b_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_b77b_S03_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S03_AXI_nmu_0} -quiet] {/bd_b77b_S03_AXI_nmu_0_top_INST } ]/bd_b77b_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_b77b_S04_AXI_rpu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S04_AXI_rpu_0 || ORIG_REF_NAME==bd_b77b_S04_AXI_rpu_0} -quiet] {/bd_b77b_S04_AXI_rpu_0_top_INST } ]/bd_b77b_S04_AXI_rpu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_b77b_S02_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S02_AXI_nmu_0} -quiet] {/bd_b77b_S02_AXI_nmu_0_top_INST } ]/bd_b77b_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_b77b_S06_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S06_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S06_AXI_nmu_0} -quiet] {/bd_b77b_S06_AXI_nmu_0_top_INST } ]/bd_b77b_S06_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_b77b_S01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S01_AXI_nmu_0} -quiet] {/bd_b77b_S01_AXI_nmu_0_top_INST } ]/bd_b77b_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_7/xdc/bd_b77b_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_b77b_S00_AXI_nmu_0} -quiet] {/bd_b77b_S00_AXI_nmu_0_top_INST } ]/bd_b77b_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_0/ip/ip_8/hdl/par/bd_b77b_MC0_ddrc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_b77b_MC0_ddrc_0 || ORIG_REF_NAME==bd_b77b_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_axi_noc_0_0/bd_soc_usart_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_soc_usart_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
