# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.runs/bd_soc_usart_u_soc_ptp_0_synth_1/bd_soc_usart_u_soc_ptp_0.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "bd_soc_usart_u_soc_ptp_0_synth_1" START { ROLLUP_AUTO }
set_param ced.repoPaths /home/adrian/Downloads/TE0950_Designs/04_AMD_Vivado_Custom_Configurable_Example
set_param bd.open.in_stealth_mode 3
set_param general.usePosixSpawnForFork 1
set_param chipscope.flow 0
set_msg_config -id {HDL-1065} -limit 10000
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
set_param ips.modRefOverrideMrefDirPath /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/mref
create_project -in_memory -part xcve2302-sfva784-1LP-e-S

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.cache/wt [current_project]
set_property parent.project_path /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/adrian/te0950_work/board_files} [current_project]
set_property board_part trenz.biz:te0950_23_1lse:part0:1.2 [current_project]
update_ip_catalog
set_property ip_output_repo /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/adrian/rv32i/soc_top_master_wrap.v
read_vhdl -vhdl2008 -library xil_defaultlib {
  /home/adrian/rv32i/riscv_pkg.vhd
  /home/adrian/rv32i/alu.vhd
  /home/adrian/rv32i/axil_soc.vhd
  /home/adrian/rv32i/control.vhd
  /home/adrian/rv32i/immgen.vhd
  /home/adrian/rv32i/regfile.vhd
  /home/adrian/rv32i/muldiv.vhd
  /home/adrian/rv32i/csr.vhd
  /home/adrian/rv32i/cpu_pipeline.vhd
  /home/adrian/rv32i/dma_burst.vhd
  /home/adrian/rv32i/dp_ram.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/eth_pkg.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/eth_tx_mii.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/eth_rx_mii.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/eth_mac.vhd
  /home/adrian/rv32i/ptp_axil_master.vhd
  /home/adrian/rv32i/mem_subsys_dma.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_pkg.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_regs.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_msg_pkg.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_clock.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_tstamp.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_tx.vhd
  /home/adrian/spw_ip/spw_fifo.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_rx.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_pdelay_fsm.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_pdelay.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_mac.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_top.vhd
  /home/adrian/vhdl_repo/IP_Cores/PTP/rtl/ptp_axil.vhd
  /home/adrian/rv32i/soc_top_master.vhd
}
read_ip -quiet /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.srcs/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0.xci

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top bd_soc_usart_u_soc_ptp_0 -part xcve2302-sfva784-1LP-e-S -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all bd_soc_usart_u_soc_ptp_0_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bd_soc_usart_u_soc_ptp_0.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file bd_soc_usart_u_soc_ptp_0_utilization_synth.rpt -pb bd_soc_usart_u_soc_ptp_0_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.runs/bd_soc_usart_u_soc_ptp_0_synth_1/bd_soc_usart_u_soc_ptp_0.dcp /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.ip_user_files/ip/bd_soc_usart_u_soc_ptp_0]} {
  catch { 
    file copy -force /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0_stub.v /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.ip_user_files/ip/bd_soc_usart_u_soc_ptp_0
  }
}

if {[file isdir /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.ip_user_files/ip/bd_soc_usart_u_soc_ptp_0]} {
  catch { 
    file copy -force /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.gen/sources_1/bd/bd_soc_usart/ip/bd_soc_usart_u_soc_ptp_0/bd_soc_usart_u_soc_ptp_0_stub.vhdl /home/adrian/vhdl_repo/IP_Cores/PTP/vivado_ptp/ptp_soc.ip_user_files/ip/bd_soc_usart_u_soc_ptp_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "bd_soc_usart_u_soc_ptp_0_synth_1" END { }
