# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.srcs/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_proc_sys_reset_0_0/ecc_soc_bd_proc_sys_reset_0_0.xci
# IP: The module: 'ecc_soc_bd_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_proc_sys_reset_0_0/ecc_soc_bd_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_proc_sys_reset_0_0/ecc_soc_bd_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.srcs/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_proc_sys_reset_0_0/ecc_soc_bd_proc_sys_reset_0_0.xci
# IP: The module: 'ecc_soc_bd_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_proc_sys_reset_0_0/ecc_soc_bd_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_proc_sys_reset_0_0/ecc_soc_bd_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
