# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.srcs/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/ecc_soc_bd_smartconnect_0_0.xci
# IP: The module: 'ecc_soc_bd_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/bd_4ec3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_4ec3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_4ec3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_4ec3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_4ec3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_4ec3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_4ec3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_4ec3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_4ec3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_4ec3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_4ec3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_4ec3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_4ec3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_4ec3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_4ec3_s00a2s_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_4ec3_sarn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_4ec3_srn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_4ec3_sawn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_4ec3_swn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_4ec3_sbn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_4ec3_m00s2a_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.srcs/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/ecc_soc_bd_smartconnect_0_0.xci
# IP: The module: 'ecc_soc_bd_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/bd_4ec3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_4ec3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_4ec3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_4ec3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_4ec3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_4ec3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_4ec3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_4ec3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_4ec3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_4ec3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_4ec3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_4ec3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_4ec3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_4ec3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_4ec3_s00a2s_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_4ec3_sarn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_4ec3_srn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_4ec3_sawn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_4ec3_swn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_4ec3_sbn_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_4ec3_m00s2a_0_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'ecc_soc_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
