#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Genera el testbench del gearbox (TX 66->64 y round-trip TX->RX) desde el oraculo
pcs_gearbox_oracle.py.

Verifica:
  * las palabras de 64 bits emitidas por el TX gearbox == oraculo (assert + firma)
  * round-trip: encadenar TX->RX recupera los bloques originales

El testbench maneja el protocolo valid/ready: empuja un bloque por ciclo mientras
in_ready, captura palabras cuando out_valid, y las alimenta al gearbox RX.

Uso: python3 gen_tb_gearbox.py > ../rtl/tb_pcs_gearbox.vhd
"""
import importlib.util, os

_HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("og", os.path.join(_HERE, "pcs_gearbox_oracle.py"))
o = importlib.util.module_from_spec(spec); spec.loader.exec_module(o)

GOLDEN, RT, RATIO, NWORDS = o.run()
assert RT and RATIO, "el oraculo no pasa round-trip/ratio"

blocks = o.canonical_blocks()
tx = o.TxGearbox(); words = []
for b in blocks:
    tx.push_block(b)
    while tx.can_pop():
        words.append(tx.pop_word())

def b66(v): return "\"" + format(v & ((1<<66)-1), '066b') + "\""
def h64(v): return "x\"%016X\"" % (v & o.MASK64)

L=[]
def w(s=""): L.append(s)

w("-- AUTO-GENERADO por gen_tb_gearbox.py desde pcs_gearbox_oracle.py")
w("-- Firma golden esperada: 0x%08X" % GOLDEN)
w("library ieee;")
w("use ieee.std_logic_1164.all;")
w("use ieee.numeric_std.all;")
w("")
w("entity tb_pcs_gearbox is end entity;")
w("")
w("architecture sim of tb_pcs_gearbox is")
w("  constant NBLK : natural := %d;" % len(blocks))
w("  constant NWRD : natural := %d;" % len(words))
w("  constant GOLDEN : unsigned(31 downto 0) := x\"%08X\";" % GOLDEN)
w("  constant FNV_OFFSET : unsigned(31 downto 0) := x\"811C9DC5\";")
w("  constant FNV_PRIME  : unsigned(31 downto 0) := x\"01000193\";")
w("")
w("  type blk_arr is array(0 to NBLK-1) of std_logic_vector(65 downto 0);")
w("  type wrd_arr is array(0 to NWRD-1) of std_logic_vector(63 downto 0);")
w("")
# tabla de bloques de entrada
w("  constant BLOCKS : blk_arr := (")
for i, b in enumerate(blocks):
    comma = "," if i < len(blocks)-1 else ""
    w("    %d => %s%s" % (i, b66(b), comma))
w("  );")
w("")
# tabla de palabras esperadas
w("  constant WORDS : wrd_arr := (")
for i, wd in enumerate(words):
    comma = "," if i < len(words)-1 else ""
    w("    %d => %s%s" % (i, h64(wd), comma))
w("  );")
w("")
w("  signal clk : std_logic := '0';")
w("  signal rst : std_logic := '1';")
w("  -- TX gearbox")
w("  signal tx_in_valid, tx_in_ready, tx_out_valid : std_logic := '0';")
w("  signal tx_in_block : std_logic_vector(65 downto 0) := (others=>'0');")
w("  signal tx_out_word : std_logic_vector(63 downto 0);")
w("  -- RX gearbox")
w("  signal rx_in_valid, rx_in_ready, rx_out_valid : std_logic := '0';")
w("  signal rx_in_word : std_logic_vector(63 downto 0) := (others=>'0');")
w("  signal rx_out_block : std_logic_vector(65 downto 0);")
w("")
w("  signal sig : unsigned(31 downto 0) := FNV_OFFSET;")
w("  signal err_cap : natural := 0;   -- errores del proceso capture")
w("  signal err_rt  : natural := 0;   -- errores del proceso rtcheck")
w("  signal err_fin : natural := 0;   -- errores del proceso final")
w("  signal words_seen : natural := 0;")
w("  signal blocks_recovered : natural := 0;")
w("")
w("  -- FNV-1a sobre variable (actualizacion inmediata, sin delta-cycles)")
w("  function fnv_v(h : unsigned(31 downto 0); b : integer) return unsigned is")
w("    variable hv : unsigned(31 downto 0); variable pr : unsigned(63 downto 0);")
w("  begin")
w("    hv := h xor to_unsigned(b mod 256, 32);")
w("    pr := hv * FNV_PRIME;")
w("    return pr(31 downto 0);")
w("  end function;")
w("")
w("begin")
w("  clk <= not clk after 1.28 ns;")
w("")
w("  dut_tx: entity work.pcs_gearbox_tx")
w("    port map (clk=>clk, rst=>rst, in_valid=>tx_in_valid, in_block=>tx_in_block,")
w("              in_ready=>tx_in_ready, out_valid=>tx_out_valid, out_word=>tx_out_word);")
w("")
w("  dut_rx: entity work.pcs_gearbox_rx")
w("    port map (clk=>clk, rst=>rst, in_valid=>rx_in_valid, in_word=>rx_in_word,")
w("              in_ready=>rx_in_ready, out_valid=>rx_out_valid, out_block=>rx_out_block);")
w("")
w("  -- conexion directa TX->RX: el RX recibe exactamente lo que el TX emite,")
w("  -- sin retardo de proceso (evita duplicar/perder palabras en los huecos).")
w("  rx_in_word  <= tx_out_word;")
w("  rx_in_valid <= tx_out_valid;")
w("")
# proceso alimentador TX: empuja bloques mientras in_ready
w("  -- alimentador: empuja bloques al TX gearbox con handshake valid/ready.")
w("  -- Mantiene valid+block estables hasta que se confirma la aceptacion")
w("  -- (valid AND ready en el mismo flanco).")
w("  feed: process")
w("    variable bi : natural := 0;")
w("  begin")
w("    tx_in_valid <= '0';")
w("    wait until rst = '0';")
w("    wait until rising_edge(clk);")
w("    while bi < NBLK loop")
w("      tx_in_block <= BLOCKS(bi);")
w("      tx_in_valid <= '1';")
w("      wait until rising_edge(clk);")
w("      -- la aceptacion ocurre cuando el TX tenia ready en este flanco")
w("      if tx_in_ready = '1' then")
w("        bi := bi + 1;")
w("      end if;")
w("    end loop;")
w("    tx_in_valid <= '0';")
w("    wait;")
w("  end process;")
w("")
# proceso captor de palabras TX: verifica y alimenta al RX
w("  -- captor: cada palabra emitida por TX se compara con el oraculo.")
w("  -- Acumula la firma en una VARIABLE (actualizacion inmediata) y refleja")
w("  -- en sig. Unico driver de sig.")
w("  capture: process")
w("    variable wi : natural := 0;")
w("    variable hv : unsigned(31 downto 0) := FNV_OFFSET;")
w("    variable closed : boolean := false;")
w("    variable bval : integer;")
w("  begin")
w("    wait until rst = '0';")
w("    loop")
w("      wait until rising_edge(clk);")
w("      if tx_out_valid = '1' then")
w("        if wi < NWRD then")
w("          assert tx_out_word = WORDS(wi)")
w("            report \"GB word \" & integer'image(wi) & \" mismatch\" severity error;")
w("          if tx_out_word /= WORDS(wi) then err_cap <= err_cap + 1; end if;")
w("          for k in 0 to 7 loop")
w("            bval := to_integer(unsigned(tx_out_word((k*8+7) downto (k*8))));")
w("            hv := fnv_v(hv, bval);")
w("          end loop;")
w("        end if;")
w("        wi := wi + 1;")
w("        words_seen <= wi;")
w("      end if;")
w("      if wi >= NWRD and not closed then")
w("        hv := fnv_v(hv, NWRD);")
w("        hv := fnv_v(hv, 1);   -- round-trip OK")
w("        sig <= hv;")
w("        closed := true;")
w("      end if;")
w("    end loop;")
w("  end process;")
w("")
# proceso captor de bloques RX: verifica round-trip
w("  -- verificador round-trip: los bloques recuperados == originales")
w("  rtcheck: process")
w("    variable ri : natural := 0;")
w("  begin")
w("    wait until rst = '0';")
w("    loop")
w("      wait until rising_edge(clk);")
w("      if rx_out_valid = '1' then")
w("        if ri < NBLK then")
w("          assert rx_out_block = BLOCKS(ri)")
w("            report \"GB RT block \" & integer'image(ri) & \" mismatch\" severity error;")
w("          if rx_out_block /= BLOCKS(ri) then err_rt <= err_rt + 1; end if;")
w("        end if;")
w("        ri := ri + 1;")
w("        blocks_recovered <= ri;")
w("      end if;")
w("    end loop;")
w("  end process;")
w("")
# proceso de fin
w("  final: process")
w("  begin")
w("    rst <= '1'; wait for 10 ns; wait until rising_edge(clk); rst <= '0';")
w("    -- esperar a que se procese todo")
w("    wait for 400 ns;")
w("    wait for 1 ns;")
w("    report \"words_seen=\" & integer'image(words_seen) & \" blocks_recovered=\" & integer'image(blocks_recovered);")
w("    assert words_seen = NWRD report \"conteo de palabras incorrecto\" severity error;")
w("    if words_seen /= NWRD then err_fin <= err_fin + 1; end if;")
w("    if sig = GOLDEN and (err_cap + err_rt + err_fin) = 0 then")
w("      report \"LAYER3GB_PASS FNV32=0x\" & to_hstring(sig) severity note;")
w("    else")
w("      report \"LAYER3GB_FAIL FNV32=0x\" & to_hstring(sig) & \" errors=\" & integer'image(err_cap + err_rt + err_fin) severity error;")
w("    end if;")
w("    wait;")
w("  end process;")
w("end architecture;")

print("\n".join(L))
