#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Genera el testbench del datapath PCS completo desde pcs_datapath_oracle.py.

Verifica:
  * palabras de linea del TX datapath == oraculo (assert + firma FNV en variable)
  * round-trip end-to-end: TX -> RX recupera (payload, is_data)

Patron robusto (aprendido en el gearbox):
  * firma acumulada en VARIABLE (no senal) -> sin problemas de delta-cycle
  * un solo driver por senal
  * conexion directa TX->RX por asignacion concurrente
  * alimentador con handshake valid/ready correcto

Uso: python3 gen_tb_datapath.py > ../rtl/tb_pcs_datapath.vhd
"""
import importlib.util, os

_HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("odp", os.path.join(_HERE, "pcs_datapath_oracle.py"))
o = importlib.util.module_from_spec(spec); spec.loader.exec_module(o)

GOLDEN, RT, NW, NR = o.run()
assert RT, "el oraculo no pasa round-trip"

stream = o.canonical_stream()
# calcular las palabras esperadas del TX
tx = o.PcsTxDatapath(); words = []
for payload, is_data in stream:
    words.extend(tx.push(payload, is_data))

def h64(v): return "x\"%016X\"" % (v & o.MASK64)

L=[]
def w(s=""): L.append(s)

w("-- AUTO-GENERADO por gen_tb_datapath.py desde pcs_datapath_oracle.py")
w("-- Firma golden esperada: 0x%08X" % GOLDEN)
w("library ieee;")
w("use ieee.std_logic_1164.all;")
w("use ieee.numeric_std.all;")
w("")
w("entity tb_pcs_datapath is end entity;")
w("")
w("architecture sim of tb_pcs_datapath is")
w("  constant NSTREAM : natural := %d;" % len(stream))
w("  constant NWRD : natural := %d;" % len(words))
w("  constant GOLDEN : unsigned(31 downto 0) := x\"%08X\";" % GOLDEN)
w("  constant FNV_OFFSET : unsigned(31 downto 0) := x\"811C9DC5\";")
w("  constant FNV_PRIME  : unsigned(31 downto 0) := x\"01000193\";")
w("")
w("  type pl_arr is array(0 to NSTREAM-1) of std_logic_vector(63 downto 0);")
w("  type bt_arr is array(0 to NSTREAM-1) of std_logic;")
w("  type wd_arr is array(0 to NWRD-1) of std_logic_vector(63 downto 0);")
w("")
w("  constant PAYLOADS : pl_arr := (")
for i,(p,d) in enumerate(stream):
    comma = "," if i < len(stream)-1 else ""
    w("    %d => %s%s" % (i, h64(p), comma))
w("  );")
w("  constant ISDATA : bt_arr := (")
for i,(p,d) in enumerate(stream):
    comma = "," if i < len(stream)-1 else ""
    w("    %d => '%d'%s" % (i, 1 if d else 0, comma))
w("  );")
w("  constant WORDS : wd_arr := (")
for i,wd in enumerate(words):
    comma = "," if i < len(words)-1 else ""
    w("    %d => %s%s" % (i, h64(wd), comma))
w("  );")
w("")
w("  signal clk : std_logic := '0';")
w("  signal rst : std_logic := '1';")
w("  -- TX datapath")
w("  signal tx_in_valid, tx_in_ready, tx_out_valid, tx_in_isdata : std_logic := '0';")
w("  signal tx_in_payload : std_logic_vector(63 downto 0) := (others=>'0');")
w("  signal tx_out_word : std_logic_vector(63 downto 0);")
w("  -- RX datapath")
w("  signal rx_in_valid, rx_in_ready, rx_out_valid, rx_out_isdata : std_logic;")
w("  signal rx_in_word : std_logic_vector(63 downto 0);")
w("  signal rx_out_payload : std_logic_vector(63 downto 0);")
w("")
w("  signal sig : unsigned(31 downto 0) := FNV_OFFSET;")
w("  signal err_cap, err_rt, err_fin : natural := 0;")
w("  signal words_seen, recs_seen : natural := 0;")
w("")
w("  function fnv_v(h : unsigned(31 downto 0); b : integer) return unsigned is")
w("    variable hv : unsigned(31 downto 0); variable pr : unsigned(63 downto 0);")
w("  begin")
w("    hv := h xor to_unsigned(b mod 256, 32); pr := hv * FNV_PRIME;")
w("    return pr(31 downto 0);")
w("  end function;")
w("")
w("begin")
w("  clk <= not clk after 1.28 ns;")
w("")
w("  dut_tx: entity work.pcs_tx_datapath")
w("    port map (clk=>clk, rst=>rst, in_valid=>tx_in_valid, in_payload=>tx_in_payload,")
w("              in_is_data=>tx_in_isdata, in_ready=>tx_in_ready,")
w("              out_valid=>tx_out_valid, out_word=>tx_out_word);")
w("")
w("  dut_rx: entity work.pcs_rx_datapath")
w("    port map (clk=>clk, rst=>rst, in_valid=>rx_in_valid, in_word=>rx_in_word,")
w("              in_ready=>rx_in_ready, out_valid=>rx_out_valid,")
w("              out_payload=>rx_out_payload, out_is_data=>rx_out_isdata);")
w("")
w("  -- conexion directa TX->RX")
w("  rx_in_word  <= tx_out_word;")
w("  rx_in_valid <= tx_out_valid;")
w("")
# alimentador con handshake
w("  feed: process")
w("    variable si : natural := 0;")
w("  begin")
w("    tx_in_valid <= '0';")
w("    wait until rst = '0';")
w("    wait until rising_edge(clk);")
w("    while si < NSTREAM loop")
w("      tx_in_payload <= PAYLOADS(si);")
w("      tx_in_isdata  <= ISDATA(si);")
w("      tx_in_valid   <= '1';")
w("      wait until rising_edge(clk);")
w("      if tx_in_ready = '1' then si := si + 1; end if;")
w("    end loop;")
w("    tx_in_valid <= '0';")
w("    wait;")
w("  end process;")
w("")
# captor de palabras TX + firma
w("  capture: process")
w("    variable wi : natural := 0;")
w("    variable hv : unsigned(31 downto 0) := FNV_OFFSET;")
w("    variable closed : boolean := false;")
w("    variable bval : integer;")
w("  begin")
w("    wait until rst = '0';")
w("    loop")
w("      wait until rising_edge(clk);")
w("      if tx_out_valid = '1' then")
w("        if wi < NWRD then")
w("          assert tx_out_word = WORDS(wi)")
w("            report \"DP word \" & integer'image(wi) & \" mismatch\" severity error;")
w("          if tx_out_word /= WORDS(wi) then err_cap <= err_cap + 1; end if;")
w("          for k in 0 to 7 loop")
w("            bval := to_integer(unsigned(tx_out_word((k*8+7) downto (k*8))));")
w("            hv := fnv_v(hv, bval);")
w("          end loop;")
w("        end if;")
w("        wi := wi + 1;")
w("        words_seen <= wi;")
w("      end if;")
w("      if wi >= NWRD and not closed then")
w("        hv := fnv_v(hv, NWRD);")
w("        hv := fnv_v(hv, 1);")
w("        sig <= hv;")
w("        closed := true;")
w("      end if;")
w("    end loop;")
w("  end process;")
w("")
# verificador round-trip end-to-end
w("  rtcheck: process")
w("    variable ri : natural := 0;")
w("    variable exp_d : std_logic;")
w("  begin")
w("    wait until rst = '0';")
w("    loop")
w("      wait until rising_edge(clk);")
w("      if rx_out_valid = '1' then")
w("        if ri < NSTREAM then")
w("          assert rx_out_payload = PAYLOADS(ri)")
w("            report \"DP RT payload \" & integer'image(ri) & \" mismatch\" severity error;")
w("          if rx_out_payload /= PAYLOADS(ri) then err_rt <= err_rt + 1; end if;")
w("          exp_d := ISDATA(ri);")
w("          assert rx_out_isdata = exp_d")
w("            report \"DP RT isdata \" & integer'image(ri) & \" mismatch\" severity error;")
w("          if rx_out_isdata /= exp_d then err_rt <= err_rt + 1; end if;")
w("        end if;")
w("        ri := ri + 1;")
w("        recs_seen <= ri;")
w("      end if;")
w("    end loop;")
w("  end process;")
w("")
w("  final: process")
w("  begin")
w("    rst <= '1'; wait for 10 ns; wait until rising_edge(clk); rst <= '0';")
w("    wait for 600 ns;")
w("    wait for 1 ns;")
w("    report \"words_seen=\" & integer'image(words_seen) & \" recs_seen=\" & integer'image(recs_seen);")
w("    assert words_seen = NWRD report \"conteo palabras incorrecto\" severity error;")
w("    if words_seen /= NWRD then err_fin <= err_fin + 1; end if;")
w("    assert recs_seen = NSTREAM report \"conteo recuperados incorrecto\" severity error;")
w("    if recs_seen /= NSTREAM then err_fin <= err_fin + 1; end if;")
w("    if sig = GOLDEN and (err_cap + err_rt + err_fin) = 0 then")
w("      report \"LAYER3DP_PASS FNV32=0x\" & to_hstring(sig) severity note;")
w("    else")
w("      report \"LAYER3DP_FAIL FNV32=0x\" & to_hstring(sig) & \" errors=\" & integer'image(err_cap+err_rt+err_fin) severity error;")
w("    end if;")
w("    wait;")
w("  end process;")
w("end architecture;")

print("\n".join(L))
