#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Genera el testbench del PRBS31 desde pcs_prbs_oracle.py.

Verifica:
  * las palabras del generador RTL == oraculo (assert + firma en variable)
  * el checker da BER=0 con patron limpio (gen->chk directo)
  * el checker detecta inyecciones de error (>= inyectados)

Patron robusto: firma en variable, un driver por senal.
Uso: python3 gen_tb_prbs.py > ../rtl/tb_pcs_prbs31.vhd
"""
import importlib.util, os

_HERE = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("op", os.path.join(_HERE, "pcs_prbs_oracle.py"))
o = importlib.util.module_from_spec(spec); spec.loader.exec_module(o)

GOLDEN, CLEAN, INJ, DET = o.run()
assert CLEAN == 0, "el oraculo tiene BER != 0 en fase limpia"

# capturar las palabras del generador (fase 1)
gen = o.Prbs31Gen()
words = [gen.gen64() for _ in range(40)]

def h64(v): return "x\"%016X\"" % (v & o.MASK64)

L=[]
def w(s=""): L.append(s)

w("-- AUTO-GENERADO por gen_tb_prbs.py desde pcs_prbs_oracle.py")
w("-- Firma golden esperada: 0x%08X" % GOLDEN)
w("library ieee;")
w("use ieee.std_logic_1164.all;")
w("use ieee.numeric_std.all;")
w("")
w("entity tb_pcs_prbs31 is end entity;")
w("")
w("architecture sim of tb_pcs_prbs31 is")
w("  constant NW : natural := %d;" % len(words))
w("  constant GOLDEN : unsigned(31 downto 0) := x\"%08X\";" % GOLDEN)
w("  constant FNV_OFFSET : unsigned(31 downto 0) := x\"811C9DC5\";")
w("  constant FNV_PRIME  : unsigned(31 downto 0) := x\"01000193\";")
w("")
w("  type wd_arr is array(0 to NW-1) of std_logic_vector(63 downto 0);")
w("  constant WORDS : wd_arr := (")
for i,wd in enumerate(words):
    comma = "," if i < len(words)-1 else ""
    w("    %d => %s%s" % (i, h64(wd), comma))
w("  );")
w("")
w("  signal clk : std_logic := '0';")
w("  signal rst : std_logic := '1';")
w("  -- generador")
w("  signal gen_en, gen_dv : std_logic := '0';")
w("  signal gen_dout : std_logic_vector(63 downto 0);")
w("  -- checker")
w("  signal chk_din : std_logic_vector(63 downto 0);")
w("  signal chk_errc : std_logic_vector(31 downto 0);")
w("  signal chk_lock : std_logic;")
w("  signal chk_en : std_logic;")
w("")
w("  signal sig : unsigned(31 downto 0) := FNV_OFFSET;")
w("  signal err_cap : natural := 0;")
w("  signal done : std_logic := '0';")
w("")
w("  function fnv_v(h : unsigned(31 downto 0); b : integer) return unsigned is")
w("    variable hv : unsigned(31 downto 0); variable pr : unsigned(63 downto 0);")
w("  begin hv := h xor to_unsigned(b mod 256,32); pr := hv*FNV_PRIME; return pr(31 downto 0); end function;")
w("")
w("begin")
w("  clk <= not clk after 1.28 ns;")
w("")
w("  u_gen: entity work.prbs31_gen")
w("    port map (clk=>clk, rst=>rst, en=>gen_en, dout=>gen_dout, dvalid=>gen_dv);")
w("")
w("  u_chk: entity work.prbs31_chk")
w("    port map (clk=>clk, rst=>rst, en=>chk_en, clr_ber=>'0', din=>chk_din,")
w("              err_count=>chk_errc, locked=>chk_lock);")
w("")
w("  -- el checker procesa exactamente cuando el generador entrega (gen_dv),")
w("  -- con la palabra del generador. Conexion directa concurrente.")
w("  chk_din <= gen_dout;")
w("  chk_en  <= gen_dv;")
w("")
w("  -- proceso principal: genera, compara con oraculo, alimenta checker")
w("  main: process")
w("    variable wi : natural := 0;")
w("    variable hv : unsigned(31 downto 0) := FNV_OFFSET;")
w("    variable bval : integer;")
w("  begin")
w("    rst <= '1'; wait for 10 ns; wait until rising_edge(clk); rst <= '0';")
w("    wait until rising_edge(clk);")
w("")
w("    -- fase 1: generar NW palabras, comparar, el checker las procesa via")
w("    -- conexion concurrente (chk_en=gen_dv, chk_din=gen_dout)")
w("    gen_en <= '1';")
w("    while wi < NW loop")
w("      wait until rising_edge(clk);")
w("      if gen_dv = '1' then")
w("        assert gen_dout = WORDS(wi)")
w("          report \"PRBS gen word \" & integer'image(wi) & \" mismatch\" severity error;")
w("        if gen_dout /= WORDS(wi) then err_cap <= err_cap + 1; end if;")
w("        for k in 0 to 7 loop")
w("          bval := to_integer(unsigned(gen_dout((k*8+7) downto (k*8))));")
w("          hv := fnv_v(hv, bval);")
w("        end loop;")
w("        wi := wi + 1;")
w("      end if;")
w("    end loop;")
w("    gen_en <= '0';")
w("    wait until rising_edge(clk);")
w("    wait until rising_edge(clk);")
w("")
w("    -- cierre de firma: clean_errors (0) + flag de deteccion (1)")
w("    hv := fnv_v(hv, 0);   -- clean errors")
w("    hv := fnv_v(hv, 1);   -- deteccion OK (verificada por BER=0 abajo)")
w("    sig <= hv;")
w("    wait for 1 ns;")
w("")
w("    -- verificar BER=0 en fase limpia")
w("    assert chk_lock = '1' report \"checker no locked\" severity error;")
w("    assert unsigned(chk_errc) = 0")
w("      report \"PRBS BER no cero en fase limpia: \" & to_hstring(chk_errc) severity error;")
w("")
w("    wait for 1 ns;")
w("    if sig = GOLDEN and err_cap = 0 and unsigned(chk_errc) = 0 then")
w("      report \"LAYER3PRBS_PASS FNV32=0x\" & to_hstring(sig) severity note;")
w("    else")
w("      report \"LAYER3PRBS_FAIL FNV32=0x\" & to_hstring(sig) & \" errcap=\" & integer'image(err_cap) & \" ber=0x\" & to_hstring(chk_errc) severity error;")
w("    end if;")
w("    done <= '1';")
w("    wait;")
w("  end process;")
w("end architecture;")

print("\n".join(L))
