# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ecc_soc_bd/ecc_soc_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecc_soc_bd || ORIG_REF_NAME==ecc_soc_bd} -quiet] -quiet

# IP: bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/ecc_soc_bd_versal_cips_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecc_soc_bd_versal_cips_0_0 || ORIG_REF_NAME==ecc_soc_bd_versal_cips_0_0} -quiet] -quiet

# Block Designs: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/bd_dfd3.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfd3 || ORIG_REF_NAME==bd_dfd3} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/ip/ip_0/bd_dfd3_pspmc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfd3_pspmc_0_0 || ORIG_REF_NAME==bd_dfd3_pspmc_0_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/ip/ip_0/ip_0/versal_cips_ps_vip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==versal_cips_ps_vip_0 || ORIG_REF_NAME==versal_cips_ps_vip_0} -quiet] -quiet

# IP: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/ip/ip_1/bd_dfd3_xram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_dfd3_xram_0 || ORIG_REF_NAME==bd_dfd3_xram_0} -quiet] -quiet

# IP: bd/ecc_soc_bd/ip/ecc_soc_bd_axi_noc_0_0/ecc_soc_bd_axi_noc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecc_soc_bd_axi_noc_0_0 || ORIG_REF_NAME==ecc_soc_bd_axi_noc_0_0} -quiet] -quiet

# IP: bd/ecc_soc_bd/ip/ecc_soc_bd_soc_ecc_0_0/ecc_soc_bd_soc_ecc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecc_soc_bd_soc_ecc_0_0 || ORIG_REF_NAME==ecc_soc_bd_soc_ecc_0_0} -quiet] -quiet

# IP: bd/ecc_soc_bd/ip/ecc_soc_bd_proc_sys_reset_0_0/ecc_soc_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecc_soc_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==ecc_soc_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ecc_soc_bd/ip/ecc_soc_bd_xlconstant_1_0/ecc_soc_bd_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecc_soc_bd_xlconstant_1_0 || ORIG_REF_NAME==ecc_soc_bd_xlconstant_1_0} -quiet] -quiet

# IP: bd/ecc_soc_bd/ip/ecc_soc_bd_smartconnect_0_0/ecc_soc_bd_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ecc_soc_bd_smartconnect_0_0 || ORIG_REF_NAME==ecc_soc_bd_smartconnect_0_0} -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/ip/ip_0/bd_dfd3_pspmc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dfd3_pspmc_0_0 || ORIG_REF_NAME==bd_dfd3_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/ip/ip_0/pspmc_v1_4/constraints/usr_constraints.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dfd3_pspmc_0_0 || ORIG_REF_NAME==bd_dfd3_pspmc_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/ip/ip_1/bd_dfd3_xram_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_dfd3_xram_0 || ORIG_REF_NAME==bd_dfd3_xram_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ip/ecc_soc_bd_versal_cips_0_0/bd_0/bd_dfd3_ooc.xdc

# XDC: /home/adrian/vhdl_repo/IP_Cores/ECC_Scrubber/vivado/ecc_soc/ecc_soc.gen/sources_1/bd/ecc_soc_bd/ecc_soc_bd_ooc.xdc
